export const theme = {
  colors: {
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-hover)',
    primaryLight: 'var(--color-primary-light)',
    primaryDark: 'var(--color-primary-dark)',
    bg: 'var(--color-bg)',
    bgCard: 'var(--color-bg-card)',
    bgSidebar: 'var(--color-bg-sidebar)',
    bgSidebarActive: 'var(--color-bg-sidebar-active)',
    bgTopbar: 'var(--color-bg-topbar)',
    text: 'var(--color-text)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    textSidebar: 'var(--color-text-sidebar)',
    textSidebarActive: 'var(--color-text-sidebar-active)',
    border: 'var(--color-border)',
    borderLight: 'var(--color-border-light)',
    success: 'var(--color-success)',
    successLight: 'var(--color-success-light)',
    warning: 'var(--color-warning)',
    warningLight: 'var(--color-warning-light)',
    danger: 'var(--color-danger)',
    dangerLight: 'var(--color-danger-light)',
    info: 'var(--color-info)',
    infoLight: 'var(--color-info-light)',
    trendUp: 'var(--color-trend-up)',
    trendDown: 'var(--color-trend-down)',
  },
  sizing: {
    sidebarWidth: 'var(--sidebar-width)',
    sidebarCollapsedWidth: 'var(--sidebar-collapsed-width)',
    topbarHeight: 'var(--topbar-height)',
    borderRadius: 'var(--border-radius)',
    borderRadiusSm: 'var(--border-radius-sm)',
    borderRadiusLg: 'var(--border-radius-lg)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  transitions: {
    fast: 'var(--transition-fast)',
    normal: 'var(--transition-normal)',
  },
} as const;

export type AppTheme = typeof theme;
